language: python
os: linux
dist: jammy # Ubuntu 22.04  if not specified, python 3.11 won't be supported
python:
  - "3.11"

install:
  - gem install webrick
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls
  - mkdir ./tools
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./tools

script:
  - black . --check
  - flake8 --max-line-length=88
  - coverage run --source=swe_app,polls manage.py test
  - coverage xml
  - ./tools/coveralls report --repo-token=$COVERALLS_REPO_TOKEN ./coverage.xml
  

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "us-west-2"
    app: "swe_app"
    env: "swe-app-env"
    bucket_name: "elasticbeanstalk-us-west-2-083086457391"
    on:
      branch: main
