language: python
os: linux
dist: jammy
python:
  - "3.11"
script: true

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "us-east-1"
    app: "swe-app"
    env: "swe-app-env"
    bucket_name: "swe-app-bucket"
    on:
      branch: main
    